import dotenv from "dotenv";

dotenv.config();

const {
    DISCORD_TOKEN,
    DISCORD_CLIENT_ID,
    DEFAULT_CHAMPIONSHIP_ID,
    DEFAULT_GAMBLING_AMOUNT,
    ADMIN_USERNAME,
    PERSISTENCE_TYPE,
    SQL_HOST,
    SQL_PORT,
    SQL_USER,
    SQL_PASSWORD,
    SQL_DATABASE,
    SQLITE_FILE
} = process.env;

if (!DISCORD_TOKEN || !DISCORD_CLIENT_ID || !DEFAULT_CHAMPIONSHIP_ID || !ADMIN_USERNAME) {
    throw new Error("Missing environment variables: DISCORD_TOKEN, DISCORD_CLIENT_ID, DEFAULT_CHAMPIONSHIP_ID, ADMIN_USERNAME");
}

export const botConfig = {
    DISCORD_TOKEN,
    DISCORD_CLIENT_ID,
    DEFAULT_CHAMPIONSHIP_ID: Number(DEFAULT_CHAMPIONSHIP_ID),
    DEFAULT_GAMBLING_AMOUNT: Number(DEFAULT_GAMBLING_AMOUNT || 1000),
    ADMIN_USERNAME,
    PERSISTENCE_TYPE: PERSISTENCE_TYPE || 'MOCK',
    SQL_HOST,
    SQL_PORT,
    SQL_USER,
    SQL_PASSWORD,
    SQL_DATABASE,
    SQLITE_FILE
};
