import dotenv from "dotenv";

dotenv.config();

const { DISCORD_TOKEN, DISCORD_CLIENT_ID, DEFAULT_CHAMPIONSHIP_ID, DEFAULT_GAMBLING_AMOUNT } = process.env;

if (!DISCORD_TOKEN || !DISCORD_CLIENT_ID || !DEFAULT_CHAMPIONSHIP_ID) {
    throw new Error("Missing environment variables: DISCORD_TOKEN, DISCORD_CLIENT_ID, DEFAULT_CHAMPIONSHIP_ID");
}

export const config = {
    DISCORD_TOKEN,
    DISCORD_CLIENT_ID,
    DEFAULT_CHAMPIONSHIP_ID: Number(DEFAULT_CHAMPIONSHIP_ID),
    DEFAULT_GAMBLING_AMOUNT: Number(DEFAULT_GAMBLING_AMOUNT || 1000)
};
